"""add_daily_stats_table

Revision ID: 8b421376ec6b
Revises: 493bf0fa2efa
Create Date: 2026-07-14 14:04:59.609520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b421376ec6b'
down_revision: Union[str, Sequence[str], None] = '493bf0fa2efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('feeding_count', sa.Integer(), nullable=False),
    sa.Column('excretion_count', sa.Integer(), nullable=False),
    sa.Column('behavior_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_index(op.f('ix_daily_stats_pet_id'), 'daily_stats', ['pet_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_user_id'), 'daily_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_stats_user_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_pet_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
