"""add_daily_stats_composite_indexes

Revision ID: f29bad3b4c50
Revises: 8b421376ec6b
Create Date: 2026-07-14 15:02:34.960535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29bad3b4c50'
down_revision: Union[str, Sequence[str], None] = '8b421376ec6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_stats_date_user', 'daily_stats', ['date', 'user_id'], unique=False)
    op.create_index('ix_daily_stats_pet_date', 'daily_stats', ['pet_id', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_stats_pet_date', table_name='daily_stats')
    op.drop_index('ix_daily_stats_date_user', table_name='daily_stats')
    # ### end Alembic commands ###
